version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: adonis
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_root_password

  backend:
    build: .
    image: student_backend:latest
    container_name: adonis_api
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - NODE_ENV=development
    ports:
      - "3333:3333"
    depends_on:
      - db

  frontend:
    build: /Users/charan/intern/FrontEnd/Training_project/
    image: student_frontend:latest
    container_name: vue_app
    restart: always
    env_file:
      - /Users/charan/intern/FrontEnd/Training_project/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
secrets:
  db_root_password:
    file: ./db_root_password.txt
volumes:
  db_data: